<a href="https://colab.research.google.com/github/Mustafizb24/gold-directional-forecasting/blob/main/gold_data_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
'''
installs yfinance, which is a free library to download market data directly from Yahoo Finance
Also imports pandas, for working with dataframes
'''

!pip install yfinance -q
import yfinance as yf
import pandas as pd

In [15]:
# Downoad daily closing prices for gold futures and the US Dollar Index
yahoo = yf.download(["GC=F", "DX-Y.NYB"], start = "2010-01-01", end = "2026-01-01", auto_adjust=True) ["Close"] #Close means it records the price at the end of each daily session

yahoo.head() #Shows the first 5 rows

[*********************100%***********************]  2 of 2 completed

Ticker       DX-Y.NYB         GC=F
Date
2010-01-04  77.529999  1117.699951
2010-01-05  77.620003  1118.099976
2010-01-06  77.489998  1135.900024
2010-01-07  77.910004  1133.099976
2010-01-08  77.470001  1138.199951

In [16]:
# Download the US 10-year Treasury yield from FRED (Federal Reserve)
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=DGS10"
fred = pd.read_csv(url, index_col = 0, parse_dates = True, na_values=".")

#Keep only 2010-2025 to match the Yahoo data for gold and dollar index
fred = fred.loc["2010-01-01":"2025-12-31"]

fred.head()

                  DGS10
observation_date
2010-01-01          NaN
2010-01-04         3.85
2010-01-05         3.77
2010-01-06         3.85
2010-01-07         3.85

In [18]:
# Combine the Yahoo and FRED data into one table, using Yahoo's trading days
raw = yahoo.join(fred, how="left")

# Rename the columns to short, clear names
raw = raw.rename(columns={"GC=F": "gold", "DX-Y.NYB": "dxy", "DGS10" : "yield_10y"})

#Save as a CSV
raw.to_csv("raw_2010_2025.csv")

raw.head()

                  dxy         gold  yield_10y
Date
2010-01-04  77.529999  1117.699951       3.85
2010-01-05  77.620003  1118.099976       3.77
2010-01-06  77.489998  1135.900024       3.85
2010-01-07  77.910004  1133.099976       3.85
2010-01-08  77.470001  1138.199951       3.83

In [19]:
#Checking number of rows and columns
print(raw.shape)

# Count missing values in each column
print(raw.isna().sum())

#Show last 5 rows
raw.tail()

(4027, 3)
dxy           2
gold          3
yield_10y    32
dtype: int64

                  dxy         gold  yield_10y
Date
2025-12-24  97.980003  4502.799805       4.15
2025-12-26  98.019997  4552.700195       4.14
2025-12-29  98.040001  4343.600098       4.12
2025-12-30  98.239998  4386.299805       4.14
2025-12-31  98.279999  4341.100098       4.18

In [ ]:
#4000 rows lines up with approximately 16 years of trading days